require 'rails_helper'

RSpec.describe Article, type: :model do

  it "is invalid without a title" do
    article = Article.new(content: "The quick brown fox jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy lions. Then he jumps over the lazy tigers. Then he jumps over the lazy elephants. Then he jumps over the lazy giraffes. Then he jumps over the lazy zebras. Then he jumps over the lazy kangaroos. Then he jumps over the lazy koalas. Then he jumps over the lazy pandas. Then he jumps over the lazy monkeys. Then he jumps over the lazy gorillas. Then he jumps over the lazy chimpanzees. Then he jumps over the lazy orangutans. Then he jumps over the lazy baboons. Then he jumps over the lazy hyenas. Then he jumps over the lazy wolves. Then he jumps over the lazy foxes. Then he jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy lions. Then he jumps over the lazy tigers. Then he jumps over the lazy elephants. Then he jumps over the lazy giraffes. Then he jumps over the lazy zebras. Then he jumps over the lazy kangaroos. Then he jumps over the lazy koalas. Then he jumps over the lazy pandas. Then he jumps over the lazy monkeys. Then he jumps over the lazy gorillas. Then he jumps over the lazy chimpanzees. Then he jumps over the lazy orangutans. Then he jumps over the lazy baboons. Then he jumps over the lazy hyenas. Then he jumps over the lazy wolves. Then he jumps over the lazy foxes. Then he jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy")
    expect(article).to be_invalid
  end

  it "is invalid without content" do
    article = Article.new(title: "New Title")
    expect(article).to be_invalid
  end

  it "is valid with title and content" do
    article = Article.new(title: "Another Title", content: "The quick brown fox jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy lions. Then he jumps over the lazy tigers. Then he jumps over the lazy elephants. Then he jumps over the lazy giraffes. Then he jumps over the lazy zebras. Then he jumps over the lazy kangaroos. Then he jumps over the lazy koalas. Then he jumps over the lazy pandas. Then he jumps over the lazy monkeys. Then he jumps over the lazy gorillas. Then he jumps over the lazy chimpanzees. Then he jumps over the lazy orangutans. Then he jumps over the lazy baboons. Then he jumps over the lazy hyenas. Then he jumps over the lazy wolves. Then he jumps over the lazy foxes. Then he jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy lions. Then he jumps over the lazy tigers. Then he jumps over the lazy elephants. Then he jumps over the lazy giraffes. Then he jumps over the lazy zebras. Then he jumps over the lazy kangaroos. Then he jumps over the lazy koalas. Then he jumps over the lazy pandas. Then he jumps over the lazy monkeys. Then he jumps over the lazy gorillas. Then he jumps over the lazy chimpanzees. Then he jumps over the lazy orangutans. Then he jumps over the lazy baboons. Then he jumps over the lazy hyenas. Then he jumps over the lazy wolves. Then he jumps over the lazy foxes. Then he jumps over the lazy dogs. Then he jumps over the lazy cats. Then he jumps over the lazy birds. Then he jumps over the lazy fish. Then he jumps over the lazy snakes. Then he jumps over the lazy turtles. Then he jumps over the lazy rabbits. Then he jumps over the lazy deer. Then he jumps over the lazy bears. Then he jumps over the lazy")
    expect(article).to be_valid
  end

end
